config-version: 2

name: "jaffle_shop"
version: "3.0.0"
require-dbt-version: ">=1.5.0"

dbt-cloud:
  project-id: 123456   # update with your project ID in workshop account!

profile: upgrading_to_fusion

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["data-tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  "dbt_date:time_zone": "America/Los_Angeles"
  # Saved query export configuration - soft blocker
  enable_saved_query_exports: true
  saved_query_export_path: "exports/saved_queries"
  # Additional variables that may cause issues
  environment: "production"  # DEPRECATED: Should use target.name
  debug_mode: true  # Used by deprecated macros
  base_url: "https://api.example.com"  # Used in deprecated var usage
  expected_rows_customers: 1000
  expected_rows_orders: 5000

# Behavior change flags for modern dbt practices and migration testing
flags:
  require_explicit_package_overrides_for_builtin_materializations: true
  require_model_names_without_spaces: true
  source_freshness_run_project_hooks: true
  restrict_direct_pg_catalog_access: false
  skip_nodes_if_on_run_start_fails: false
  state_modified_compare_more_unrendered_values: true
  require_yaml_configuration_for_mf_time_spines: false
  require_batched_execution_for_custom_microbatch_strategy: false
  require_nested_cumulative_type_params: false
  validate_macro_args: true
  require_generic_test_arguments_property: true

# Saved queries configuration disabled - represents soft blocker for Fusion migration
# saved-queries:
#   jaffle_shop:
#     +export_as: table
#     +export_limit: 10000
#     +export_to_cloud: true

models:
  jaffle_shop:
    staging:
      +materialized: view
      # Deprecated test patterns model
      +meta:
        stg_deprecated_tests:
          +materialized: view
          +warn_error: true # DEPRECATED: Should use warn-error-options
    marts:
      +materialized: table
      +persist_docs:  # Missing + prefix (dbt Core ignores, Fusion validates)
        relation: true
        columns: true
      # Iceberg table configurations - soft blocker
      +meta:
        order_history_iceberg:
          +materialized: iceberg_table
          +file_format: parquet
          +table_type: iceberg
          +partition_by: ["order_date"]
          +clustered_by: ["customer_id"]
          +table_properties:
            "+format-version": "2"
            "+write.target-file-size-bytes": "134217728"
            "+write.delete.mode": "merge-on-read"
      # Custom materialization models
        advanced_cloned_table:
          +materialized: view
        customer_scd2:
          +materialized: table
      # Models with advanced query comments
        logging_dependent_model:
          +query_comment: "Advanced query comment model with logging"
      # High-frequency event processing
        order_events_microbatch:
          +materialized: incremental
          +incremental_strategy: delete+insert
          +unique_key: order_id