upgrading_to_fusion:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: YDA41575
      user: training_user
      role: transformer

      password: dbt_Training123!

      database: dbt_learn
      warehouse: transformer_coalesce
      schema: dbt_jb
      threads: 4
      client_session_keep_alive: False